name: env variables
on: push
env:
    WF_ENV: avaliable to all jobs

jobs:
    log-env:
        runs-on: ubuntu-latest
        env:
            JOB_ENV: avaliable to all jobs
        steps:
            run: |
                echo "WF_ENV: ${WF_ENV}"
                echo "JOB_ENV: ${JOB_ENV}"
